//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesPedidos
    {
        public int id { get; set; }
        public int DetallesPedidosID { get; set; }
        public int PedidoID { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public float Cantidad { get; set; }
        public Nullable<int> Producto_id { get; set; }
    
        public virtual Pedidoes Pedidoes { get; set; }
        public virtual Productoes Productoes { get; set; }
    }
}
