//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleyes
    {
        public int EmpleyeId { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public decimal Salario { get; set; }
        public int Bono { get; set; }
        public System.DateTime FehcaNacimiento { get; set; }
        public System.DateTime HoraInicio { get; set; }
        public string Correo { get; set; }
        public string URL { get; set; }
        public int TipoDocuemntoID { get; set; }
    
        public virtual TipoDocumentoes TipoDocumentoes { get; set; }
    }
}
