//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productoes()
        {
            this.DetallesPedidos = new HashSet<DetallesPedidos>();
            this.ProveedoresProductoes = new HashSet<ProveedoresProductoes>();
        }
    
        public int id { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public System.DateTime FechaUltimaCompras { get; set; }
        public float Bodega { get; set; }
        public string Comentario { get; set; }
        public Nullable<float> Cantidad { get; set; }
        public string Discriminator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesPedidos> DetallesPedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProveedoresProductoes> ProveedoresProductoes { get; set; }
    }
}
