//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedoresProductoes
    {
        public int ProveedorProductoID { get; set; }
        public int ProveedorID { get; set; }
        public int id { get; set; }
    
        public virtual Productoes Productoes { get; set; }
        public virtual Proveedors Proveedors { get; set; }
    }
}
